### ISSUE TITLE
Resources Ordner

### ISSUE THREAD

**Issue by krakowski** [ProPra16/programmierpraktikum-abschlussprojekt-iuvba#4]
Hey,

da das mit dem manuellen Kopieren der FXML- und CSS-Dateien in den build Ordner
etwas umständlich und auf dauer bestimmt nervig ist:

im Ordner "main" innerhalb des Projektes kann man einen Ordner "resources" (er muss exakt
so heißen) erstellen, in den alle Dateien, die das Programm zum Starten benötigt, hineinkopiert
werden können. Gradle ist standarmäßig so konfiguriert, dass es diese Dateien dann mitkopiert.

`LayoutMenu.fxml` kann dann beispielsweise durch
`MenuGUI.class.getResources("/LayoutMenu.fxml")` referenziert werden.

Viele Grüße,
Filip

**Comment by lomoz** [comment]
Ich habe erstmal ein ganz anderes Problem. Ich wollte heute an dem Projekt weiter arbeiten, wollte es vorher noch einmal ausführen, aber bekomme jetzt einen Error ohne im Vergleich zu gestern irgendwas geändert zu haben.

> /Library/Java/JavaVirtualMachines/jdk1.8.0_65.jdk/Contents/Home/bin/java -Didea.launcher.port=7535 "-Didea.launcher.bin.path=/Applications/IntelliJ IDEA CE.app/Contents/bin" -Dfile.encoding=UTF-8 -classpath "/Library/Java/JavaVirtualMachines/jdk1.8.0_65.jdk/Contents/Home/jre/lib/charsets.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_65.jdk/Contents/Home/jre/lib/deploy.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_65.jdk/Contents/Home/jre/lib/ext/cldrdata.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_65.jdk/Contents/Home/jre/lib/ext/dnsns.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_65.jdk/Contents/Home/jre/lib/ext/jaccess.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_65.jdk/Contents/Home/jre/lib/ext/jfxrt.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_65.jdk/Contents/Home/jre/lib/ext/localedata.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_65.jdk/Contents/Home/jre/lib/ext/nashorn.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_65.jdk/Contents/Home/jre/lib/ext/sunec.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_65.jdk/Contents/Home/jre/lib/ext/sunjce_provider.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_65.jdk/Contents/Home/jre/lib/ext/sunpkcs11.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_65.jdk/Contents/Home/jre/lib/ext/zipfs.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_65.jdk/Contents/Home/jre/lib/javaws.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_65.jdk/Contents/Home/jre/lib/jce.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_65.jdk/Contents/Home/jre/lib/jfr.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_65.jdk/Contents/Home/jre/lib/jfxswt.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_65.jdk/Contents/Home/jre/lib/jsse.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_65.jdk/Contents/Home/jre/lib/management-agent.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_65.jdk/Contents/Home/jre/lib/plugin.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_65.jdk/Contents/Home/jre/lib/resources.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_65.jdk/Contents/Home/jre/lib/rt.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_65.jdk/Contents/Home/lib/ant-javafx.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_65.jdk/Contents/Home/lib/dt.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_65.jdk/Contents/Home/lib/javafx-mx.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_65.jdk/Contents/Home/lib/jconsole.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_65.jdk/Contents/Home/lib/packager.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_65.jdk/Contents/Home/lib/sa-jdi.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_65.jdk/Contents/Home/lib/tools.jar:/Applications/IntelliJ IDEA CE.app/Contents/lib/idea_rt.jar" com.intellij.rt.execution.application.AppMain de.hhu.propra16.MenuGUI
> Exception in thread "main" java.lang.ClassNotFoundException: de.hhu.propra16.MenuGUI
>     at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
>     at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
>     at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
>     at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
>     at java.lang.Class.forName0(Native Method)
>     at java.lang.Class.forName(Class.java:264)
>     at com.intellij.rt.execution.application.AppMain.main(AppMain.java:122)

Process finished with exit code 1

Ich verstehe nicht wieso dieser Fehler auftritt. Und es ist ziemlich blöd, weil ich jetzt gar nicht am Projekt weiter arbeiten kann..

**Comment by krakowski** [comment]
Hey,

habe gerade das Projekt geladen und bei mir funktioniert alles normal.
Versuch mal oben in der Menüleiste `Build -> Rebuild Project` und danach nochmal starten.

---

**Edit**

Ein kleiner Fehler ist dennoch beim Kopieren der Dateien ins Projekt entstanden:

In `LayoutMenu.fxml` wird der Controller mit `fx:controller="FensterController"` angegeben.
An dieser Stelle müsste `fx:controller="de.hhu.propra16.FensterController"` stehen.

Viele Grüße,
Filip

**Comment by padgm** [comment]
Vielen Dank für den Hinweis! Habs verbessert.

**Comment by lomoz** [comment]
Bei mir funktioniert es immer noch nicht.
Habe vorher auch nochmal die aktuellste Version gepullt und und den rebuild versucht..

**Comment by krakowski** [comment]
Hey,

bei mir funktioniert folgendes:
1. `git clone git@github.com:ProPra16/programmierpraktikum-abschlussprojekt-iuvba.git`
2. In IntelliJ `File -> New... -> Project from Existing Sources...` und dort die `build.gradle` auswählen
3. Alle Häkchen entfernen, `Use graddle wrapper task configuration` auswählen und auf OK
4. Rechtsklick auf `MenuGUI` und `Run 'MenuGUI.main()'` auswählen

Sollte ein Language Level Fehler auftreten dann folgendes versuchen:
1. `File -> Project Structure...`
2. Unter `Project language level` den Wert auf `8 - Lambdas, type annotations etc.` setzen
3. `Apply` anklicken und Schritt 4 von vorhin nochmal versuchen.

Viele Grüße,
Filip

**Comment by lomoz** [comment]
Habe es jetzt nach der Anleitung versucht, das neue Projekt wurde auch dementsprechend erstellt.
Allerdings bekomme ich jetzt im FensterController eine Fehlermeldung.
Lade den Screenshot davon mal hier hoch.
![bildschirmfoto 2016-07-14 um 14 33 19](https://cloud.githubusercontent.com/assets/19909168/16839580/21205206-49d0-11e6-8cf9-50aa739662aa.png)

**Comment by krakowski** [comment]
Hey,

das ist der Language Level Fehler von dem ich gesprochen habe (siehe letzte Antwort).

Viele Grüße,
Filip

**Comment by lomoz** [comment]
Ok, jetzt hat's funktioniert, dankeschön :)
